/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <UIKit/UIKit.h>
#import <UIKit/UIControl.h>

#import "NSCoding-Protocol.h"

@class NSMutableArray, UIColor, UIView;

@interface UISegmentedControlProxy : UIControl <NSCoding>
{
	@public
    NSMutableArray *_segments;
    int _selectedSegment;
    int _highlightedSegment;
    UIView *_removedSegment;
    id _delegate;
    UIColor *_tintColor;
    int _barStyle;
    void *_appearance;
    struct {
        unsigned int style:3;
        unsigned int size:2;
        unsigned int showsDisclosure:1;
        unsigned int delegateSelectedSegmentChanged:1;
        unsigned int delegateDisclosureButtonClicked:1;
        unsigned int delegateAlwaysNotifiesDelegateOfSegmentClicks:1;
        unsigned int momentaryClick:1;
        unsigned int dontAlwaysToggleForTwoSegments:1;
        unsigned int tracking:1;
        unsigned int mouseInside:1;
        unsigned int autosizeToFitSegments:1;
        unsigned int isSizingToFit:1;
        unsigned int autosizeText:1;
        unsigned int transparentBackground:1;
    } _segmentedControlFlags;
}

+ (float)defaultHeightForStyle:(int)arg1 size:(int)arg2;
+ (float)defaultHeightForStyle:(int)arg1;
- (void)updateForMiniBarState:(BOOL)arg1;
- (struct CGPoint)_offsetForMiniBarState:(BOOL)arg1;
- (void)_commonSegmentedControlInit;
- (id)initWithFrame:(struct CGRect)arg1;
- (id)initWithItems:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (void)dealloc;
- (void)_resetForAppearanceChange;
//- (void)_setSegmentedControlAppearance:(CDStruct_eaecd812 *)arg1;
@property(nonatomic) int segmentedControlStyle; // @dynamic segmentedControlStyle;
- (int)controlSize;
- (void)setControlSize:(int)arg1;
- (int)segmentControlStyle;
- (void)setSegmentControlStyle:(int)arg1;
@property(nonatomic, getter=isMomentary) BOOL momentary; // @dynamic momentary;
- (void)setAlwaysToggleForTwoSegments:(BOOL)arg1;
- (void)_setAutosizeText:(BOOL)arg1;
@property(strong, nonatomic) UIColor *tintColor; // @synthesize tintColor=_tintColor;
- (void)setBarStyle:(int)arg1;
- (int)barStyle;
- (void)setTransparentBackground:(BOOL)arg1;
- (BOOL)transparentBackground;
- (void)insertSegmentWithTitle:(id)arg1 atIndex:(unsigned int)arg2 animated:(BOOL)arg3;
- (void)insertSegmentWithImage:(id)arg1 atIndex:(unsigned int)arg2 animated:(BOOL)arg3;
- (void)removeSegmentAtIndex:(unsigned int)arg1 animated:(BOOL)arg2;
- (void)removeAllSegments;
- (void)setTitle:(id)arg1 forSegmentAtIndex:(unsigned int)arg2;
- (id)titleForSegmentAtIndex:(unsigned int)arg1;
- (void)setImage:(id)arg1 forSegmentAtIndex:(unsigned int)arg2;
- (id)imageForSegmentAtIndex:(unsigned int)arg1;
- (void)setWidth:(float)arg1 forSegmentAtIndex:(unsigned int)arg2;
- (float)widthForSegmentAtIndex:(unsigned int)arg1;
- (void)setContentOffset:(struct CGSize)arg1 forSegmentAtIndex:(unsigned int)arg2;
- (struct CGSize)contentOffsetForSegmentAtIndex:(unsigned int)arg1;
- (void)setEnabled:(BOOL)arg1 forSegmentAtIndex:(unsigned int)arg2;
- (BOOL)isEnabledForSegmentAtIndex:(unsigned int)arg1;
@property(readonly, nonatomic) unsigned int numberOfSegments; // @dynamic numberOfSegments;
@property(nonatomic) int selectedSegmentIndex; // @dynamic selectedSegmentIndex;
- (void)sizeToFit;
- (void)setFrame:(struct CGRect)arg1;
- (struct CGSize)sizeThatFits:(struct CGSize)arg1;
- (void)layoutSubviews;
- (BOOL)shouldTrack;
- (void)highlightSegment:(int)arg1;
- (void)mouseDown:(struct __GSEvent *)arg1;
- (BOOL)pointMostlyInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (BOOL)pointMostlyInside:(struct CGPoint)arg1 forEvent:(struct __GSEvent *)arg2;
- (void)mouseDragged:(struct __GSEvent *)arg1;
- (void)mouseUp:(struct __GSEvent *)arg1;
- (void)touchesBegan:(id)arg1 withEvent:(id)arg2;
- (void)touchesMoved:(id)arg1 withEvent:(id)arg2;
- (void)touchesEnded:(id)arg1 withEvent:(id)arg2;
- (BOOL)useBlockyMagnificationInClassic;

@end

