/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <UIKit/UIKit.h>
#import <UIKit/UIControl.h>

@class UITabBarButtonBadge, UITabBarButtonLabel, UITabBarSelectionIndicatorView, UIView;

@interface UITabBarButtonProxy : UIControl
{
	@public
    struct CGRect _hitRect;
    UIView *_info;
    UITabBarButtonLabel *_label;
    UITabBarButtonBadge *_badge;
    UITabBarSelectionIndicatorView *_selectedIndicator;
    BOOL _onState;
    BOOL _barHeight;
    BOOL _badgeAnimated;
    struct UIEdgeInsets _infoInsets;
}

+ (id)_defaultLabelFont;
+ (id)_defaultLabelColor;
+ (id)_donePushButton;
- (id)initWithImage:(id)arg1 selectedImage:(id)arg2 label:(id)arg3 withInsets:(struct UIEdgeInsets)arg4;
- (void)dealloc;
- (void)setImage:(id)arg1;
- (void)_setTabBarHitRect:(struct CGRect)arg1;
- (struct CGRect)_tabBarHitRect;
- (void)_showSelectedIndicator:(BOOL)arg1 changeSelection:(BOOL)arg2;
- (void)_setSelected:(BOOL)arg1;
- (void)_positionBadge;
- (void)setFrame:(struct CGRect)arg1;
- (void)_setBadgeValue:(id)arg1;
- (void)_badgeAnimationDidStop:(id)arg1 finished:(id)arg2;
- (void)_setBadgeAnimated:(BOOL)arg1;
- (void)setEnabled:(BOOL)arg1;
- (BOOL)pointInside:(struct CGPoint)arg1 forEvent:(struct __GSEvent *)arg2;
- (BOOL)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)layoutSubviews;
- (void)_setOn:(BOOL)arg1;
- (BOOL)_isOn;
- (void)_setBarHeight:(float)arg1;
- (BOOL)_useBarHeight;

@end

