/*
 *     Generated by class-dump 3.1.1.
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2006 by Steve Nygard.
 */

@class CALayer;
#import <UIKit/UIView.h>

@interface UITableViewCellContentViewProxy : UIView 
{
    CALayer *_mask;
}

-(id) _cell;

@end

