/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <UIKit/UIKit.h>
#import <UIKit/UILabel.h>

@class UITextRenderingAttributes;

@interface UITabBarButtonLabelProxy : UILabel
{
	@public
    float _boundsWidth;
    UITextRenderingAttributes *_attributes;
}

- (void)dealloc;
- (id)_attributes;
- (void)sizeToFitBounds:(struct CGRect)arg1;

@end

