/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import <UIKit/UIKit.h>
#import <UIKit/UIControl.h>

@class UIColor, UILabel, UISelectionIndicatorView, UIToolbarButtonBadge, UIView;

@interface UIToolbarButtonProxy : UIControl
{
	@public
    struct CGRect _hitRect;
    UIView *_info;
    UILabel *_label;
    UIToolbarButtonBadge *_badge;
    UISelectionIndicatorView *_selectedIndicator;
    int _barStyle;
    int _style;
    struct UIEdgeInsets _glowAdjust;
    BOOL _onState;
    BOOL _barHeight;
    BOOL _badgeAnimated;
    BOOL _bezel;
    float _width;
    float _labelHeight;
    struct UIEdgeInsets _infoInsets;
    UIColor *_tintColor;
    BOOL _isAnimatedTrashButton;
    BOOL _imageIsBackground;
}

+ (id)_defaultLabelFont;
+ (id)_defaultLabelColor;
+ (id)_pushButtonWithBarStyle:(int)arg1 withStyle:(int)arg2 withTintColor:(id)arg3;
+ (void)_adjustPushButton:(id)arg1 withBarStyle:(int)arg2 withStyle:(int)arg3 withTintColor:(id)arg4 isMinibar:(BOOL)arg5;
- (id)initWithImage:(id)arg1 selectedImage:(id)arg2 label:(id)arg3 labelHeight:(float)arg4 withBarStyle:(int)arg5 withStyle:(int)arg6 withInsets:(struct UIEdgeInsets)arg7 possibleTitles:(id)arg8 withTintColor:(id)arg9 bezel:(BOOL)arg10 imageInsets:(struct UIEdgeInsets)arg11 glowInsets:(struct UIEdgeInsets)arg12;
- (id)initWithImage:(id)arg1 selectedImage:(id)arg2 highlightImage:(id)arg3 label:(id)arg4 labelHeight:(float)arg5 withBarStyle:(int)arg6 withStyle:(int)arg7 withInsets:(struct UIEdgeInsets)arg8 possibleTitles:(id)arg9 withTintColor:(id)arg10 bezel:(BOOL)arg11 imageInsets:(struct UIEdgeInsets)arg12 glowInsets:(struct UIEdgeInsets)arg13 imageIsBackground:(BOOL)arg14;
- (void)dealloc;
- (void)setSizesToFitImage:(BOOL)arg1;
- (void)_sizeView:(id)arg1 toPossibleTitles:(id)arg2 selectedTitle:(id)arg3;
- (void)setImage:(id)arg1;
- (void)_setButtonBarHitRect:(struct CGRect)arg1;
- (struct CGRect)_buttonBarHitRect;
- (void)_showSelectedIndicator:(BOOL)arg1 changeSelection:(BOOL)arg2;
- (void)_setSelected:(BOOL)arg1;
- (void)setUseSelectedImage:(BOOL)arg1;
- (void)_positionBadge;
- (void)setFrame:(struct CGRect)arg1;
- (void)_setBadgeValue:(id)arg1;
- (void)_badgeAnimationDidStop:(id)arg1 finished:(id)arg2;
- (void)_setBadgeAnimated:(BOOL)arg1;
- (void)_setInfoWidth:(float)arg1;
- (void)setEnabled:(BOOL)arg1;
- (BOOL)pointInside:(struct CGPoint)arg1 forEvent:(struct __GSEvent *)arg2;
- (BOOL)pointInside:(struct CGPoint)arg1 withEvent:(id)arg2;
- (id)hitTest:(struct CGPoint)arg1 forEvent:(struct __GSEvent *)arg2;
- (id)hitTest:(struct CGPoint)arg1 withEvent:(id)arg2;
- (void)setHighlighted:(BOOL)arg1;
- (void)_adjustPushButton:(BOOL)arg1;
- (void)layoutSubviews;
- (BOOL)_isBordered;
- (void)_setOn:(BOOL)arg1;
- (BOOL)_isOn;
- (void)_animateImage:(float)arg1 withButtonBar:(id)arg2 target:(id)arg3 didFinishSelector:(SEL)arg4;
- (void)_animateImage:(float)arg1 withButtonBar:(id)arg2;
- (void)_setBarHeight:(float)arg1;
- (BOOL)_useBarHeight;
- (void)setTintColor:(id)arg1;
- (void)_adjustPushButtonWithBarStyle:(int)arg1 withTintColor:(id)arg2 isMinibar:(BOOL)arg3;
@property(nonatomic, getter=isAnimatedTrashButton) BOOL animatedTrashButton; // @synthesize animatedTrashButton=_isAnimatedTrashButton;

@end

