/*
 *     Generated by class-dump 3.3.3 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2010 by Steve Nygard.
 */

#import "UIToolbarButtonProxy.h"

@class NSString;

@interface UIToolbarTextButtonProxy : UIToolbarButtonProxy
{
	@public
    NSString *_title;
    NSString *_selectedTitle;
}

- (id)initWithTitle:(id)arg1 selectedTitle:(id)arg2 withFont:(id)arg3 withBarStyle:(int)arg4 withStyle:(int)arg5 withTitleWidth:(float)arg6 possibleTitles:(id)arg7 withTintColor:(id)arg8;
- (void)dealloc;
- (void)_setSelected:(BOOL)arg1;
- (id)_scriptingInfo;

@end

