/***** DO NOT EDIT THIS FILE *****/
// MTTests.js generated by MonkeyTalk at 2012-08-03 15:34:43 MDT

load("libs/MonkeyTalkAPI.js");


var MTTests = {};

/*** script -- list ***/
MTTests.list = function(app) {
	MT.Script.call(this, app, "list.mt");
};

MTTests.list.prototype = new MT.Script;

MTTests.list.prototype.call = function() {
	//run: list.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.list = function() {
	return new MTTests.list(this);
};

/*** script -- ordinals ***/
MTTests.ordinals = function(app) {
	MT.Script.call(this, app, "ordinals.mt");
};

MTTests.ordinals.prototype = new MT.Script;

MTTests.ordinals.prototype.call = function() {
	//run: ordinals.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.ordinals = function() {
	return new MTTests.ordinals(this);
};

/*** script -- reset ***/
MTTests.reset = function(app) {
	MT.Script.call(this, app, "reset.mt");
};

MTTests.reset.prototype = new MT.Script;

MTTests.reset.prototype.call = function() {
	//run: reset.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.reset = function() {
	return new MTTests.reset(this);
};

/*** script -- resetZoo ***/
MTTests.resetZoo = function(app) {
	MT.Script.call(this, app, "resetZoo.mt");
};

MTTests.resetZoo.prototype = new MT.Script;

MTTests.resetZoo.prototype.call = function() {
	//run: resetZoo.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.resetZoo = function() {
	return new MTTests.resetZoo(this);
};

/*** script -- touch ***/
MTTests.touch = function(app) {
	MT.Script.call(this, app, "touch.mt");
};

MTTests.touch.prototype = new MT.Script;

MTTests.touch.prototype.call = function() {
	//run: touch.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.touch = function() {
	return new MTTests.touch(this);
};

/*** script -- web ***/
MTTests.web = function(app) {
	MT.Script.call(this, app, "web.mt");
};

MTTests.web.prototype = new MT.Script;

MTTests.web.prototype.call = function() {
	//run: web.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.web = function() {
	return new MTTests.web(this);
};

/*** script -- zoo ***/
MTTests.zoo = function(app) {
	MT.Script.call(this, app, "zoo.mt");
};

MTTests.zoo.prototype = new MT.Script;

MTTests.zoo.prototype.call = function() {
	//run: zoo.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.zoo = function() {
	return new MTTests.zoo(this);
};

