/***** DO NOT EDIT THIS FILE *****/
// DemoAppTests.js generated by MonkeyTalk at 2012-10-08 16:31:01 MDT

load("libs/MonkeyTalkAPI.js");


var DemoAppTests = {};

/*** script -- form ***/
DemoAppTests.form = function(app) {
	MT.Script.call(this, app, "form.mt");
};

DemoAppTests.form.prototype = new MT.Script;

DemoAppTests.form.prototype.call = function() {
	//run: form.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.form = function() {
	return new DemoAppTests.form(this);
};

/*** script -- hierarchy ***/
DemoAppTests.hierarchy = function(app) {
	MT.Script.call(this, app, "hierarchy.mt");
};

DemoAppTests.hierarchy.prototype = new MT.Script;

DemoAppTests.hierarchy.prototype.call = function() {
	//run: hierarchy.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.hierarchy = function() {
	return new DemoAppTests.hierarchy(this);
};

/*** script -- login ***/
DemoAppTests.login = function(app) {
	MT.Script.call(this, app, "login.mt");
};

DemoAppTests.login.prototype = new MT.Script;

DemoAppTests.login.prototype.call = function(usr, pw) {
	//run: login.mt
	MT.Script.prototype.call(this, usr, pw);
};

MT.Application.prototype.login = function() {
	return new DemoAppTests.login(this);
};

/*** script -- loginRun ***/
DemoAppTests.loginRun = function(app) {
	MT.Script.call(this, app, "loginRun.mt");
};

DemoAppTests.loginRun.prototype = new MT.Script;

DemoAppTests.loginRun.prototype.call = function() {
	//run: loginRun.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.loginRun = function() {
	return new DemoAppTests.loginRun(this);
};

/*** script -- t ***/
DemoAppTests.t = function(app) {
	MT.Script.call(this, app, "t.mt");
};

DemoAppTests.t.prototype = new MT.Script;

DemoAppTests.t.prototype.call = function() {
	//run: t.mt
	MT.Script.prototype.call(this);
};

MT.Application.prototype.t = function() {
	return new DemoAppTests.t(this);
};

